create database NHATHUOC;

use NHATHUOC;

CREATE TABLE HoaDonNhap (
    MaHDN NVARCHAR PRIMARY KEY,
    NgayThang NVARCHAR(10) NOT NULL,
    NhaCungCap NVARCHAR(100) NOT NULL,
    TongTien FLOAT NOT NULL,
    NguoiGiao NVARCHAR(50) NOT NULL,
    NguoiNhan NVARCHAR(50) NOT NULL
);
CREATE TABLE HoaDonXuat (
    MaHDX NVARCHAR PRIMARY KEY,
    NgayThang NVARCHAR(10) NOT NULL,
    NhaCungCap NVARCHAR(100) NOT NULL,
    TongTien FLOAT NOT NULL
);

